In [1]:
#
# Imports
#
# %matplotlib inline
import os
import sqlite3
from argparse import Namespace
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.font_manager import fontManager, FontProperties
from sqlalchemy import __version__ as sqlalchemy_version
from sqlalchemy import inspect
from sqlalchemy.sql import func
from astropy.constants import c as lightspeed
from astropy.table import Table, MaskedColumn
#
# DESI software
#
from desitarget.targetmask import (desi_mask, mws_mask, bgs_mask)
from desisim.spec_qa import redshifts as dsq_z
from desispec import __version__ as desispec_version
#
# Paths to files, etc.
#
reference_run = '19.12'
program = 'dark'
# basedir = os.path.join(os.environ['DESI_ROOT'], 'datachallenge', 'reference_runs', reference_run)
# basedir = '/global/project/projectdirs/desi/spectro/redux/'
basedir = '/global/project/projectdirs/desi/spectro/redux/'
surveydir = os.environ['DESISURVEY_OUTPUT'] = os.path.join(basedir, 'daily')
targetdir = os.path.join(basedir, 'targets')
fibassigndir = os.path.join(basedir, 'fiberassign')
os.environ['DESI_SPECTRO_REDUX'] = os.path.join(basedir, 'spectro', 'redux')
os.environ['DESI_SPECTRO_SIM'] = os.path.join(basedir, 'spectro', 'sim')
os.environ['PIXPROD'] = 'daily'
os.environ['SPECPROD'] = 'daily'
reduxdir = os.path.join(os.environ['DESI_SPECTRO_REDUX'], os.environ['SPECPROD'])
simdatadir = os.path.join(os.environ['DESI_SPECTRO_SIM'], os.environ['PIXPROD'])
os.environ['DESI_SPECTRO_DATA'] = simdatadir
#
# Working directory.
#
workingdir = os.getcwd()
print(desispec_version)

0.42.0.dev5189

In [2]:
import pandas as pd
from pandas import DataFrame

conn = sqlite3.connect('TestDB.db')  
c = conn.cursor()

read1 = pd.read_csv (r'/global/cfs/cdirs/desi/spectro/redux/daily/exposure_tables/202012/exposure_table_20201201.csv')
read1.to_sql('202012', conn, if_exists='append', index = False) # Insert the values from the csv file into the table 

# read2 = pd.read_csv (r'C:/global/cfs/cdirs/desi/spectro/redux/daily/exposure_tables/202101.csv')
# read2.to_sql('202101', conn, if_exists='append', index = False) # Insert the values from the csv file into the table 

# read3 = pd.read_csv (r'C:/global/cfs/cdirs/desi/spectro/redux/daily/exposure_tables/202102.csv')
# read3.to_sql('202102', conn, if_exists='append', index = False) # Insert the values from the csv file into the table 

# read4 = pd.read_csv (r'C:/global/cfs/cdirs/desi/spectro/redux/daily/exposure_tables/202103.csv')
# read4.to_sql('202103', conn, if_exists='append', index = False) # Insert the values from the csv file into the table 

# read5 = pd.read_csv (r'C:/global/cfs/cdirs/desi/spectro/redux/daily/exposure_tables/202104.csv')
# read5.to_sql('202104', conn, if_exists='append', index = False) # Insert the values from the csv file into the table 


                 
conn.commit()

In [27]:
import csv
import sqlite3
import glob
import os
import re
# number = 0


def do_directory(dirname, db, lst, df):
    global number
    for root, dirs, files in os.walk(dirname): 
        for filename in files:
            if filename not in lst:
                if bool(re.match("^exposure_table_[0-9]{8}\.csv$", filename)):
                    lst.append(filename)
                    do_directory(dirname, db, lst, df)
#                     number += 1
                    print(filename, filename[15:23])
                    return do_file(dirname + filename, db, filename[15:23], df)
            

def do_file(filename, db, table_name, df):
#     x = ('r'+"'"+filename+"'")
    read2 = pd.read_csv(filename)
    df = df.append(read2, sort = False)
#     display(df)
    df.to_sql('FINAL', db, if_exists='replace', index = False)
    db.commit()
    return df
    
#         with open(filename) as f:
#             with db:
#                 data = csv.DictReader(f)
#                 cols = data.fieldnames
#                 table=os.path.splitext(os.path.basename(filename))[0]

#                 sql = 'drop table if exists "{}"'.format(table)
#                 db.execute(sql)

#                 sql = 'create table "{table}" ( {cols} )'.format(
#                     table=table,
#                     cols=','.join('"{}"'.format(col) for col in cols))
#                 db.execute(sql)

#                 sql = 'insert into "{table}" values ( {vals} )'.format(
#                     table=table,
#                     vals=','.join('?' for col in cols))
#                 db.executemany(sql, (list(map(row.get, cols)) for row in data))

In [30]:

import pandas as pd
from pandas import DataFrame
final_dataframe = pd.DataFrame()

conne = sqlite3.connect('Test.db')  
c = conne.cursor()
conne.commit()
final_dataframe = do_directory('/global/cfs/cdirs/desi/spectro/redux/daily/exposure_tables/202012/', conne,[], final_dataframe)
display(final_dataframe)

final_dataframe = do_directory('/global/cfs/cdirs/desi/spectro/redux/daily/exposure_tables/202101/', conne,[], final_dataframe)
display(final_dataframe)
final_dataframe = do_directory('/global/cfs/cdirs/desi/spectro/redux/daily/exposure_tables//', conne,[], final_dataframe)
display(final_dataframe)202102
final_dataframe = do_directory('/global/cfs/cdirs/desi/spectro/redux/daily/exposure_tables/202103/', conne,[], final_dataframe)
display(final_dataframe)
final_dataframe = do_directory('/global/cfs/cdirs/desi/spectro/redux/daily/exposure_tables/202104/', conne,[], final_dataframe)
display(final_dataframe)

exposure_table_20201223.csv 20201223
exposure_table_20201220.csv 20201220
exposure_table_20201216.csv 20201216
exposure_table_20201211.csv 20201211
exposure_table_20201212.csv 20201212
exposure_table_20201222.csv 20201222
exposure_table_20201201.csv 20201201
exposure_table_20201218.csv 20201218
exposure_table_20201213.csv 20201213
exposure_table_20201215.csv 20201215
exposure_table_20201219.csv 20201219
exposure_table_20201217.csv 20201217
exposure_table_20201221.csv 20201221
exposure_table_20201206.csv 20201206
exposure_table_20201209.csv 20201209
exposure_table_20201214.csv 20201214

,EXPID,EXPTIME,OBSTYPE,SPECTROGRAPHS,CAMWORD,TILEID,NIGHT,EXPFLAG,HEADERERR,SURVEY,SEQNUM,SEQTOT,PROGRAM,MJD-OBS,REQRA,REQDEC,TARGTRA,TARGTDEC,COMMENTS
0,67584,0.0,zero,123456789,a0123456789,-99,20201214,0,|,1,1,25,calib zeros for nightly bias,59197.935223,-99.99,-89.990,355.189140,31.963300,|
1,67585,0.0,zero,123456789,a0123456789,-99,20201214,0,|,1,2,25,calib zeros for nightly bias,59197.935993,-99.99,-89.990,355.189140,31.963300,|
2,67586,0.0,zero,123456789,a0123456789,-99,20201214,0,|,1,3,25,calib zeros for nightly bias,59197.936742,-99.99,-89.990,355.189141,31.963299,|
3,67587,0.0,zero,123456789,a0123456789,-99,20201214,0,|,1,4,25,calib zeros for nightly bias,59197.937523,-99.99,-89.990,355.189140,31.963300,|
4,67588,0.0,zero,123456789,a0123456789,-99,20201214,0,|,1,5,25,calib zeros for nightly bias,59197.938280,-99.99,-89.990,355.189140,31.963300,|
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,67771,900.0,science,123456789,a0123456789,80608,20201214,0,|,1,1,1,sv1 elg tile 80608,59198.412345,106.74,56.200,106.735850,56.204201,|
74,67781,900.0,science,123456789,a0123456789,80609,20201214,0,|,1,1,1,sv1 qso+lrg tile 80609,59198.433999,150.12,2.206,150.123908,2.199590,|
75,67782,900.0,science,123456789,a0123456789,80609,20201214,0,|,1,1,1,sv1 qso+lrg tile 80609,59198.447208,150.12,2.206,150.122921,2.199880,|
76,67783,900.0,science,123456789,a0123456789,80609,20201214,0,|,1,1,1,sv1 qso+lrg tile 80609,59198.460417,150.12,2.206,150.122009,2.200101,|
77,67784,900.0,science,123456789,a0123456789,80609,20201214,0,|,1,1,1,sv1 qso+lrg tile 80609,59198.473563,150.12,2.206,150.121150,2.200230,|

exposure_table_20210109.csv 20210109
exposure_table_20210107.csv 20210107
exposure_table_20210105.csv 20210105
exposure_table_20210102.csv 20210102
exposure_table_20210103.csv 20210103
exposure_table_20210113.csv 20210113
exposure_table_20210116.csv 20210116
exposure_table_20210101.csv 20210101
exposure_table_20210130.csv 20210130
exposure_table_20210112.csv 20210112
exposure_table_20210114.csv 20210114
exposure_table_20210115.csv 20210115
exposure_table_20210110.csv 20210110
exposure_table_20210111.csv 20210111
exposure_table_20210106.csv 20210106
exposure_table_20210108.csv 20210108
exposure_table_20210131.csv 20210131

,EXPID,EXPTIME,OBSTYPE,SPECTROGRAPHS,CAMWORD,TILEID,NIGHT,EXPFLAG,HEADERERR,SURVEY,SEQNUM,SEQTOT,PROGRAM,MJD-OBS,REQRA,REQDEC,TARGTRA,TARGTDEC,COMMENTS
0,67584,0.0000,zero,123456789,a0123456789,-99,20201214,0,|,1,1,25,calib zeros for nightly bias,59197.935223,-99.99,-89.99,355.189140,31.963300,|
1,67585,0.0000,zero,123456789,a0123456789,-99,20201214,0,|,1,2,25,calib zeros for nightly bias,59197.935993,-99.99,-89.99,355.189140,31.963300,|
2,67586,0.0000,zero,123456789,a0123456789,-99,20201214,0,|,1,3,25,calib zeros for nightly bias,59197.936742,-99.99,-89.99,355.189141,31.963299,|
3,67587,0.0000,zero,123456789,a0123456789,-99,20201214,0,|,1,4,25,calib zeros for nightly bias,59197.937523,-99.99,-89.99,355.189140,31.963300,|
4,67588,0.0000,zero,123456789,a0123456789,-99,20201214,0,|,1,5,25,calib zeros for nightly bias,59197.938280,-99.99,-89.99,355.189140,31.963300,|
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,74004,120.0392,flat,123456789,a0123456789,-99,20210131,0,|,1,2,3,calib desi-calib-02 leds only,59246.519549,-99.99,-89.99,254.345514,31.963300,|
85,74005,120.0378,flat,123456789,a0123456789,-99,20210131,0,|,1,3,3,calib desi-calib-02 leds only,59246.521687,-99.99,-89.99,254.345514,31.963300,|
86,74008,120.0362,flat,123456789,a0123456789,-99,20210131,0,|,1,1,3,calib desi-calib-03 leds only,59246.524131,-99.99,-89.99,254.345514,31.963299,|
87,74009,120.0370,flat,123456789,a0123456789,-99,20210131,0,|,1,2,3,calib desi-calib-03 leds only,59246.526266,-99.99,-89.99,254.345514,31.963300,|
88,74010,120.0374,flat,123456789,a0123456789,-99,20210131,0,|,1,3,3,calib desi-calib-03 leds only,59246.528403,-99.99,-89.99,254.345514,31.963300,|

exposure_table_20210223.csv 20210223
exposure_table_20210202.csv 20210202
exposure_table_20210228.csv 20210228
exposure_table_20210212.csv 20210212
exposure_table_20210220.csv 20210220
exposure_table_20210221.csv 20210221
exposure_table_20210214.csv 20210214
exposure_table_20210219.csv 20210219
exposure_table_20210203.csv 20210203
exposure_table_20210206.csv 20210206
exposure_table_20210217.csv 20210217
exposure_table_20210201.csv 20210201
exposure_table_20210215.csv 20210215
exposure_table_20210211.csv 20210211
exposure_table_20210222.csv 20210222
exposure_table_20210213.csv 20210213
exposure_table_20210224.csv 20210224
exposure_table_20210204.csv 20210204
exposure_table_20210208.csv 20210208
exposure_table_20210205.csv 20210205
exposure_table_20210216.csv 20210216
exposure_table_20210218.csv 20210218

,EXPID,EXPTIME,OBSTYPE,SPECTROGRAPHS,CAMWORD,TILEID,NIGHT,EXPFLAG,HEADERERR,SURVEY,...,REQRA,REQDEC,TARGTRA,TARGTDEC,COMMENTS,PURPOSE,FA_SURV,BADCAMWORD,BADAMPS,LASTSTEP
0,67584,0.0000,zero,123456789.0,a0123456789,-99,20201214,0,|,1.0,...,-99.99,-89.99,355.189140,31.963300,|,NaN,NaN,NaN,NaN,NaN
1,67585,0.0000,zero,123456789.0,a0123456789,-99,20201214,0,|,1.0,...,-99.99,-89.99,355.189140,31.963300,|,NaN,NaN,NaN,NaN,NaN
2,67586,0.0000,zero,123456789.0,a0123456789,-99,20201214,0,|,1.0,...,-99.99,-89.99,355.189141,31.963299,|,NaN,NaN,NaN,NaN,NaN
3,67587,0.0000,zero,123456789.0,a0123456789,-99,20201214,0,|,1.0,...,-99.99,-89.99,355.189140,31.963300,|,NaN,NaN,NaN,NaN,NaN
4,67588,0.0000,zero,123456789.0,a0123456789,-99,20201214,0,|,1.0,...,-99.99,-89.99,355.189140,31.963300,|,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,76822,600.0629,science,NaN,a0123456789,80735,20210218,|,|,NaN,...,NaN,NaN,250.425242,36.960270,|,sv,sv1,NaN,b9C,all
87,76823,600.0697,science,NaN,a0123456789,80735,20210218,|,|,NaN,...,NaN,NaN,250.424450,36.960400,|,sv,sv1,NaN,b9C,all
88,76824,300.0768,science,NaN,a0123456789,80733,20210218,|,|,NaN,...,NaN,NaN,199.094830,18.296851,|,sv,sv1,NaN,b9C,all
89,76825,300.0706,science,NaN,a0123456789,80733,20210218,|,|,NaN,...,NaN,NaN,199.094150,18.296630,|,sv,sv1,NaN,b9C,all
90,76826,300.0725,science,NaN,a0123456789,80733,20210218,|,|,NaN,...,NaN,NaN,199.093592,18.296440,|,sv,sv1,NaN,b9C,all

exposure_table_20210328.csv 20210328
exposure_table_20210312.csv 20210312
exposure_table_20210325.csv 20210325
exposure_table_20210309.csv 20210309
exposure_table_20210320.csv 20210320
exposure_table_20210304.csv 20210304
exposure_table_20210316.csv 20210316
exposure_table_20210326.csv 20210326
exposure_table_20210314.csv 20210314
exposure_table_20210307.csv 20210307
exposure_table_20210321.csv 20210321
exposure_table_20210318.csv 20210318
exposure_table_20210319.csv 20210319
exposure_table_20210306.csv 20210306
exposure_table_20210308.csv 20210308
exposure_table_20210311.csv 20210311
exposure_table_20210313.csv 20210313
exposure_table_20210331.csv 20210331
exposure_table_20210324.csv 20210324
exposure_table_20210305.csv 20210305
exposure_table_20210317.csv 20210317
exposure_table_20210327.csv 20210327
exposure_table_20210315.csv 20210315
exposure_table_20210322.csv 20210322

,EXPID,EXPTIME,OBSTYPE,SPECTROGRAPHS,CAMWORD,TILEID,NIGHT,EXPFLAG,HEADERERR,SURVEY,...,REQRA,REQDEC,TARGTRA,TARGTDEC,COMMENTS,PURPOSE,FA_SURV,BADCAMWORD,BADAMPS,LASTSTEP
0,67584,0.0000,zero,123456789.0,a0123456789,-99,20201214,0,|,1.0,...,-99.99,-89.99,355.189140,31.963300,|,NaN,NaN,NaN,NaN,NaN
1,67585,0.0000,zero,123456789.0,a0123456789,-99,20201214,0,|,1.0,...,-99.99,-89.99,355.189140,31.963300,|,NaN,NaN,NaN,NaN,NaN
2,67586,0.0000,zero,123456789.0,a0123456789,-99,20201214,0,|,1.0,...,-99.99,-89.99,355.189141,31.963299,|,NaN,NaN,NaN,NaN,NaN
3,67587,0.0000,zero,123456789.0,a0123456789,-99,20201214,0,|,1.0,...,-99.99,-89.99,355.189140,31.963300,|,NaN,NaN,NaN,NaN,NaN
4,67588,0.0000,zero,123456789.0,a0123456789,-99,20201214,0,|,1.0,...,-99.99,-89.99,355.189140,31.963300,|,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,81533,621.9263,science,NaN,a0123456789,80899,20210322,|,|,NaN,...,NaN,NaN,241.000171,14.997250,|,commissioning,sv1,NaN,NaN,all
83,81534,624.2284,science,NaN,a0123456789,80902,20210322,|,|,NaN,...,NaN,NaN,247.800671,32.375050,|,commissioning,sv1,NaN,NaN,all
84,81535,624.2243,science,NaN,a0123456789,80902,20210322,|,|,NaN,...,NaN,NaN,247.800159,32.375061,|,commissioning,sv1,NaN,NaN,all
85,81536,749.3930,science,NaN,a0123456789,80861,20210322,|,|,NaN,...,NaN,NaN,250.000009,23.098681,|,commissioning,sv1,NaN,NaN,all
86,81537,749.4052,science,NaN,a0123456789,80861,20210322,|,|,NaN,...,NaN,NaN,249.999400,23.098660,|,commissioning,sv1,NaN,NaN,all

exposure_table_20210419.csv 20210419
exposure_table_20210406.csv 20210406
exposure_table_20210429.csv 20210429
exposure_table_20210428.csv 20210428
exposure_table_20210414.csv 20210414
exposure_table_20210404.csv 20210404
exposure_table_20210430.csv 20210430
exposure_table_20210413.csv 20210413
exposure_table_20210401.csv 20210401
exposure_table_20210425.csv 20210425
exposure_table_20210411.csv 20210411
exposure_table_20210412.csv 20210412
exposure_table_20210407.csv 20210407
exposure_table_20210409.csv 20210409
exposure_table_20210424.csv 20210424
exposure_table_20210403.csv 20210403
exposure_table_20210420.csv 20210420
exposure_table_20210410.csv 20210410
exposure_table_20210417.csv 20210417
exposure_table_20210402.csv 20210402
exposure_table_20210405.csv 20210405
exposure_table_20210416.csv 20210416
exposure_table_20210423.csv 20210423
exposure_table_20210421.csv 20210421
exposure_table_20210408.csv 20210408
exposure_table_20210418.csv 20210418
exposure_table_20210415.csv 20210415
exposure_table_20210422.csv 20210422

,EXPID,EXPTIME,OBSTYPE,SPECTROGRAPHS,CAMWORD,TILEID,NIGHT,EXPFLAG,HEADERERR,SURVEY,...,REQRA,REQDEC,TARGTRA,TARGTDEC,COMMENTS,PURPOSE,FA_SURV,BADCAMWORD,BADAMPS,LASTSTEP
0,67584,0.0000,zero,123456789.0,a0123456789,-99,20201214,0,|,1.0,...,-99.99,-89.99,355.189140,31.963300,|,NaN,NaN,NaN,NaN,NaN
1,67585,0.0000,zero,123456789.0,a0123456789,-99,20201214,0,|,1.0,...,-99.99,-89.99,355.189140,31.963300,|,NaN,NaN,NaN,NaN,NaN
2,67586,0.0000,zero,123456789.0,a0123456789,-99,20201214,0,|,1.0,...,-99.99,-89.99,355.189141,31.963299,|,NaN,NaN,NaN,NaN,NaN
3,67587,0.0000,zero,123456789.0,a0123456789,-99,20201214,0,|,1.0,...,-99.99,-89.99,355.189140,31.963300,|,NaN,NaN,NaN,NaN,NaN
4,67588,0.0000,zero,123456789.0,a0123456789,-99,20201214,0,|,1.0,...,-99.99,-89.99,355.189140,31.963300,|,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,86013,1820.0476,science,NaN,a0123456789,80962,20210422,aborted|,|,NaN,...,NaN,NaN,240.007431,70.008531,For EXPTIME: req=1800.0 but hdu=1820.0476|,commissioning,sv1,NaN,NaN,all
57,86015,1820.0504,science,NaN,a0123456789,80968,20210422,aborted|,|,NaN,...,NaN,NaN,270.020560,70.007490,For EXPTIME: req=1800.0 but hdu=1820.0504|,commissioning,sv1,NaN,NaN,all
58,86017,1820.0495,science,NaN,a0123456789,80954,20210422,aborted|,|,NaN,...,NaN,NaN,194.952871,75.006650,For EXPTIME: req=1800.0 but hdu=1820.0495|,commissioning,sv1,NaN,NaN,all
59,86019,1820.0541,science,NaN,a0123456789,80960,20210422,aborted|,|,NaN,...,NaN,NaN,224.971008,75.009240,For EXPTIME: req=1800.0 but hdu=1820.0541|,commissioning,sv1,NaN,NaN,all
60,86021,1820.0638,science,NaN,a0123456789,80966,20210422,aborted|,|,NaN,...,NaN,NaN,254.989829,75.010480,For EXPTIME: req=1800.0 but hdu=1820.0638|,commissioning,sv1,NaN,NaN,all